### ISSUE TITLE
Milestone 1: Reminders/To-Do List Screen

### ISSUE THREAD

**Issue by lorenzomiro** [school-stop-squad/School-Stop#1]
**Required Stories**
- [x] Users can view a scrolling list of reminders needed to get done for their classes @lorenzomiro @andrealabra 
- [x] Users can add/remove items to the scrolling list of reminders @sid-pandya 
- [x] Users can view up to 10 reminders on their list of reminders @andrealabra @sid-pandya @lorenzomiro 

**Stretch Goals**
- [ ] Users can view many reminders through the use of infinite scroll
