### ISSUE TITLE
Milestone 2: Posts/Support Screen

### ISSUE THREAD

**Issue by lorenzomiro** [school-stop-squad/School-Stop#2]
**Required Stories**
- [x] Users can view a feed of posts (of 10 posts) that contain photos of their homework/assignments @andrealabra @sid-pandya 
- [x] Users can post photos of their assignments to the feed of homework/assignments @lorenzomiro 

**Stretch Goals**
- [ ] Users can like posts that appear in their feed
- [x] Users can comment on posts seen in their feed
- [ ] Users can view a feed of many posts using infinite scroll
