### ISSUE TITLE
Milestone 3: Grade Calculator Screen

### ISSUE THREAD

**Issue by lorenzomiro** [school-stop-squad/School-Stop#3]
**Required Stories**
- [ ] Users can view their current grade on the screen.
- [ ] Users can calculate the minimum required grade they need (using [Rogerhub's Final Grade Calculator](https://rogerhub.com/))  on a final exam to earn a target grade.

**Stretch Goals**

- [ ] Users can view the graded assignments to view how their average grade is calculated
