### ISSUE TITLE
Milestone 4: Video Tutorial Screen

### ISSUE THREAD

**Issue by lorenzomiro** [school-stop-squad/School-Stop#4]
**Required Stories**
- [ ] Users can search for video tutorial links using the YouTube API @sid-pandya @andrealabra 
- [ ] Users can view selected videos from a scrolling list to get help on certain homework assignments @lorenzomiro 

**Stretch Goals**

- [ ] Users can view YouTube videos in landscape mode
